server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html; # This redirects all routes to index.html
    }
}

# Serve Frontend Files
#     location / {
#         root /usr/share/nginx/html;
#         try_files $uri $uri/ /index.html;
#     }

#     # PROXY API REQUESTS (Production equivalent of your Vite proxy)
#     location /api/ {
#         proxy_pass https://api.bloodshot.in/api/;
#         proxy_set_header Host api.bloodshot.in;
#         proxy_set_header X-Real-IP $remote_addr;
#     }