import type { OrderApi } from "@/core/modals/order";

export default [
  {
    id: 35624367,
    user_id: 101,
    order_date: "2026-04-01T10:00:00Z",
    order_status: "Order processing",
    subtotal: 420,
    total_amount: 440,
    payment_method: "CARD",
    transaction_id: "TXN-A1",
    payment_status: "Paid",
    shipping_fee: 20,
    shipping_address: {
      name: "Makenna Mango",
      email: "makenna@example.com",
      contact: "9988776655",
      city: "Delhi",
      state: "Delhi",
      country: "India",
      address_id: 1,
      shipping_address: "West Avenue 21",
      zip_code: "110001",
      paymentMode: "CARD",
    },
    tracking_number: "TRK1001",
    orderItems: [{ id: 1, quantity: 2, price: 220, product_id: 10, item_img: "", item_name: "Orange" }],
  },
  {
    id: 35624368,
    user_id: 102,
    order_date: "2026-04-02T08:00:00Z",
    order_status: "Shipped",
    subtotal: 390,
    total_amount: 410,
    payment_method: "UPI",
    transaction_id: "TXN-A2",
    payment_status: "Paid",
    shipping_fee: 20,
    shipping_address: {
      name: "Phillip Vaccaro",
      email: "phillip@example.com",
      contact: "9876543210",
      city: "Pune",
      state: "Maharashtra",
      country: "India",
      address_id: 2,
      shipping_address: "Skyline Road 9",
      zip_code: "411001",
      paymentMode: "UPI",
    },
    tracking_number: "TRK1002",
    orderItems: [{ id: 2, quantity: 1, price: 410, product_id: 11, item_img: "", item_name: "Peaches" }],
  },
  {
    id: 35624369,
    user_id: 103,
    order_date: "2026-04-03T07:30:00Z",
    order_status: "Delivered",
    subtotal: 380,
    total_amount: 400,
    payment_method: "CARD",
    transaction_id: "TXN-A3",
    payment_status: "Paid",
    shipping_fee: 20,
    shipping_address: {
      name: "Madelyn Botosh",
      email: "madelyn@example.com",
      contact: "9765432109",
      city: "Mumbai",
      state: "Maharashtra",
      country: "India",
      address_id: 3,
      shipping_address: "Palm Street 18",
      zip_code: "400001",
      paymentMode: "CARD",
    },
    tracking_number: "TRK1003",
    orderItems: [
      { id: 3, quantity: 2, price: 120, product_id: 12, item_img: "", item_name: "Bananas" },
      { id: 4, quantity: 1, price: 160, product_id: 13, item_img: "", item_name: "Mango" },
    ],
  },
  {
    id: 35624370,
    user_id: 104,
    order_date: "2026-04-04T11:45:00Z",
    order_status: "Order processing",
    subtotal: 440,
    total_amount: 460,
    payment_method: "COD",
    transaction_id: "TXN-A4",
    payment_status: "Unpaid",
    shipping_fee: 20,
    shipping_address: {
      name: "Allison Levin",
      email: "allison@example.com",
      contact: "9123456789",
      city: "Kolkata",
      state: "West Bengal",
      country: "India",
      address_id: 4,
      shipping_address: "Green Park 7",
      zip_code: "700001",
      paymentMode: "COD",
    },
    tracking_number: "TRK1004",
    orderItems: [{ id: 5, quantity: 1, price: 460, product_id: 14, item_img: "", item_name: "Apple" }],
  },
  {
    id: 35624371,
    user_id: 105,
    order_date: "2026-04-05T14:20:00Z",
    order_status: "Cancelled",
    subtotal: 300,
    total_amount: 320,
    payment_method: "CARD",
    transaction_id: "TXN-A5",
    payment_status: "Pending",
    shipping_fee: 20,
    shipping_address: {
      name: "Olivia Vera",
      email: "olivia@example.com",
      contact: "9011122233",
      city: "Bengaluru",
      state: "Karnataka",
      country: "India",
      address_id: 5,
      shipping_address: "Hill View 3",
      zip_code: "560001",
      paymentMode: "CARD",
    },
    tracking_number: "TRK1005",
    orderItems: [{ id: 6, quantity: 1, price: 320, product_id: 15, item_img: "", item_name: "Grapes" }],
  },
] as OrderApi[];