import type { Product } from "@/core/modals/product";

export default [
  {
    id: 1,
    name: 'SonicWave Wireless Earbuds',
    price: 79.99,
    description: 'True wireless sound with active noise cancellation and 24-hour battery life.',
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df',
    rating: 4.7,
    reviewCount: 850,
    inStock: true,
    category: 'Electronics',
    reviews: [
      {
        id: '1',
        productId: '1',
        userName: 'Alex Johnson',
        userImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d',
        rating: 5,
        comment: 'These earbuds are amazing! The noise cancellation is top-notch.',
        title: 'Best earbuds I\'ve ever owned',
        reviewDate: new Date('2024-03-15'),
      },
      {
        id: '2',
        productId: '1',
        userName: 'Sarah Miller',
        userImageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330',
        rating: 4,
        comment: 'Great sound quality, but they sometimes slip out during heavy running.',
        title: 'Solid but fit could be better',
        reviewDate: new Date('2024-03-20'),
      },
      {
        id: '3',
        productId: '1',
        userName: 'David Chen',
        userImageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e',
        rating: 5,
        comment: 'The battery life actually exceeds the 24 hours for me. Very impressed.',
        title: 'Killer battery life',
        reviewDate: new Date('2024-04-02'),
      }
    ],
  },
  {
    id: 31,
    name: 'UltraView 27-inch Monitor',
    price: 249.5,
    description: '4K UHD resolution with ultra-slim bezels and HDR10 support for stunning visuals.',
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf',
    rating: 4.5,
    reviewCount: 320,
    inStock: true,
    category: 'Electronics',
    reviews: [
      {
        id: '4',
        productId: '2',
        userName: 'Jordan P.',
        userImageUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6',
        rating: 5,
        comment: 'Crystal clear display. The 4K makes a huge difference for video editing.',
        title: 'Stunning Visuals',
        reviewDate: new Date('2024-01-12'),
      },
      {
        id: '5',
        productId: '2',
        userName: 'Elena R.',
        userImageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1',
        rating: 4,
        comment: 'Great monitor, though the built-in speakers are a bit weak. Use external ones.',
        title: 'Perfect for work',
        reviewDate: new Date('2024-02-05'),
      },
      {
        id: '6',
        productId: '2',
        userName: 'Marcus T.',
        userImageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d',
        rating: 4,
        comment: 'Slim bezels look fantastic in a dual-monitor setup.',
        title: 'Very sleek design',
        reviewDate: new Date('2024-02-18'),
      }
    ]
  },
  {
    id: 301,
    name: 'MagCharge Power Bank',
    price: 45.0,
    description: '10,000mAh portable charger with magnetic wireless charging for latest smartphones.',
    image: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5',
    rating: 4.3,
    reviewCount: 115,
    inStock: true,
    category: 'Electronics',
    reviews: [
      {
        id: '7',
        productId: '3',
        userName: 'Riley K.',
        userImageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9',
        rating: 4,
        comment: 'The magnet is strong and stays on my phone even in my pocket.',
        title: 'Reliable Magnetic Connection',
        reviewDate: new Date('2024-03-01'),
      },
      {
        id: '8',
        productId: '3',
        userName: 'Sam V.',
        userImageUrl: 'https://images.unsplash.com/photo-1488161628813-04466f872be2',
        rating: 3,
        comment: 'Charges a bit slow compared to a cable, but the convenience is great.',
        title: 'Convenient but slow',
        reviewDate: new Date('2024-03-10'),
      },
      {
        id: '9',
        productId: '3',
        userName: 'Taylor B.',
        userImageUrl: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea',
        rating: 5,
        comment: 'Perfect for travel. Small enough to fit anywhere.',
        title: 'Travel Essential',
        reviewDate: new Date('2024-03-25'),
      }
    ]
  },
  {
    id: 4,
    name: 'Neon Mechanical Keyboard',
    price: 120.0,
    description: 'RGB backlit mechanical keyboard with tactile blue switches and aluminum frame.',
    image: 'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae',
    rating: 4.8,
    reviewCount: 540,
    inStock: false,
    category: 'Electronics',
    reviews: [
      {
        id: '10',
        productId: '4',
        userName: 'GamerGuy99',
        userImageUrl: 'https://images.unsplash.com/photo-1521119956141-ef544c7e5a8f',
        rating: 5,
        comment: 'The clicky switches feel amazing. Lighting is fully customizable.',
        title: 'A Gamer\'s Dream',
        reviewDate: new Date('2024-01-20'),
      },
      {
        id: '11',
        productId: '4',
        userName: 'Jessica L.',
        userImageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb',
        rating: 5,
        comment: 'Very sturdy build quality. The aluminum frame feels premium.',
        title: 'High Quality Build',
        reviewDate: new Date('2024-02-14'),
      },
      {
        id: '12',
        productId: '4',
        userName: 'Kevin M.',
        userImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d',
        rating: 4,
        comment: 'Blue switches are quite loud, so be careful if you work in an open office!',
        title: 'Loud but satisfying',
        reviewDate: new Date('2024-03-05'),
      }
    ]
  },
  {
    id: 5,
    name: 'ErgoFlow Mesh Chair',
    price: 189.99,
    description: 'Ergonomic office chair with lumbar support, adjustable armrests, and breathable mesh.',
    image: 'https://images.unsplash.com/photo-1688578735352-9a6f2ac3b70a',
    rating: 4.6,
    reviewCount: 210,
    inStock: true,
    category: 'Home & Office',
    reviews: [
      {
        id: '13',
        productId: '5',
        userName: 'WorkFromHomeDad',
        userImageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e',
        rating: 5,
        comment: 'Saved my back during long 10-hour shifts. The mesh is very breathable.',
        title: 'Bye Bye Back Pain',
        reviewDate: new Date('2024-01-30'),
      },
      {
        id: '14',
        productId: '5',
        userName: 'Sophie Q.',
        userImageUrl: 'https://images.unsplash.com/photo-1517365830460-955ce3ccd263',
        rating: 4,
        comment: 'Assembly took about 45 minutes, but the instructions were clear.',
        title: 'Great chair, okay assembly',
        reviewDate: new Date('2024-02-10'),
      },
      {
        id: '15',
        productId: '5',
        userName: 'Brian H.',
        userImageUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7',
        rating: 5,
        comment: 'Adjustable armrests are a game changer for my desk height.',
        title: 'Perfectly Adjustable',
        reviewDate: new Date('2024-03-12'),
      }
    ]
  },
  {
    id: 6,
    name: 'Minimalist Oak Desk',
    price: 310.0,
    description: 'Solid oak wood desk with a clean, Scandinavian design and hidden cable management.',
    image: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd',
    rating: 4.9,
    reviewCount: 88,
    inStock: true,
    category: 'Home & Office',
    reviews: [
      {
        id: '16',
        productId: '6',
        userName: 'Laura W.',
        userImageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2',
        rating: 5,
        comment: 'The wood is beautiful and heavy. Real quality furniture.',
        title: 'Absolutely Gorgeous',
        reviewDate: new Date('2024-02-22'),
      },
      {
        id: '17',
        productId: '6',
        userName: 'Tom S.',
        userImageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d',
        rating: 5,
        comment: 'The cable management tray underneath keeps everything so tidy.',
        title: 'Design meets Function',
        reviewDate: new Date('2024-03-05'),
      },
      {
        id: '18',
        productId: '6',
        userName: 'Mia J.',
        userImageUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80',
        rating: 4,
        comment: 'Slightly smaller than I imagined, but fits my laptop and monitor perfectly.',
        title: 'Sleek and Compact',
        reviewDate: new Date('2024-03-20'),
      }
    ]
  },
  {
    id: 7,
    name: 'Smart LED Desk Lamp',
    price: 34.99,
    description: 'Dimmable LED lamp with color temperature control and built-in USB charging port.',
    image: 'https://images.unsplash.com/photo-1534073828943-f801091bb18c',
    rating: 4.4,
    reviewCount: 156,
    inStock: true,
    category: 'Home & Office',
    reviews: [
      {
        id: '19',
        productId: '7',
        userName: 'Chris E.',
        userImageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e',
        rating: 5,
        comment: 'Being able to switch between warm and cool light is great for late night reading.',
        title: 'Versatile Lighting',
        reviewDate: new Date('2024-01-15'),
      },
      {
        id: '20',
        productId: '7',
        userName: 'Nina G.',
        userImageUrl: 'https://images.unsplash.com/photo-1554151228-14d9def656e4',
        rating: 4,
        comment: 'USB port charges my phone while I sleep. Very handy.',
        title: 'Functional Lamp',
        reviewDate: new Date('2024-02-28'),
      },
      {
        id: '21',
        productId: '7',
        userName: 'Leo X.',
        userImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d',
        rating: 4,
        comment: 'The touch controls are a little sensitive, but it works well.',
        title: 'Good value',
        reviewDate: new Date('2024-03-10'),
      }
    ]
  },
  {
    id: 8,
    name: 'Canvas Wall Art Set',
    price: 55.0,
    description: 'A set of 3 abstract landscape prints on premium canvas with black floating frames.',
    image: 'https://images.unsplash.com/photo-1696862048447-3ab8435ce5f1',
    rating: 4.7,
    reviewCount: 42,
    inStock: true,
    category: 'Home & Office',
    reviews: [
      {
        id: '22',
        productId: '8',
        userName: 'Alice M.',
        userImageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330',
        rating: 5,
        comment: 'Looked exactly like the photos. Really pulled my living room together.',
        title: 'Modern and Chic',
        reviewDate: new Date('2024-01-05'),
      },
      {
        id: '23',
        productId: '8',
        userName: 'Derek F.',
        userImageUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6',
        rating: 4,
        comment: 'Frames are plastic, not wood, but you can’t tell once they are on the wall.',
        title: 'Nice addition',
        reviewDate: new Date('2024-02-12'),
      },
      {
        id: '24',
        productId: '8',
        userName: 'Isabella C.',
        userImageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1',
        rating: 5,
        comment: 'Great value for a 3-piece set. Installation was easy.',
        title: 'Love these!',
        reviewDate: new Date('2024-03-01'),
      }
    ]
  },
  {
    id: 9,
    name: 'GripMax Yoga Mat',
    price: 39.99,
    description: 'Eco-friendly non-slip yoga mat with alignment lines and extra cushioning.',
    image: 'https://images.unsplash.com/photo-1592432678016-e910b452f9a2',
    rating: 4.8,
    reviewCount: 1200,
    inStock: true,
    category: 'Fitness',
    reviews: [
      {
        id: '25',
        productId: '9',
        userName: 'Yogi_Sarah',
        userImageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2',
        rating: 5,
        comment: 'I don\'t slide at all, even in hot yoga. Best mat I’ve owned.',
        title: 'Incredible Grip',
        reviewDate: new Date('2024-03-10'),
      },
      {
        id: '26',
        productId: '9',
        userName: 'Mark T.',
        userImageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d',
        rating: 4,
        comment: 'Extra thick which is great for my knees. Has a slight rubber smell at first.',
        title: 'Very Comfortable',
        reviewDate: new Date('2024-03-15'),
      },
      {
        id: '27',
        productId: '9',
        userName: 'Emma D.',
        userImageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb',
        rating: 5,
        comment: 'The alignment lines really help with my form during practice.',
        title: 'Alignment lines are a plus',
        reviewDate: new Date('2024-04-01'),
      }
    ]
  },
  {
    id: 10,
    name: 'Adjustable Dumbbell Set',
    price: 299.0,
    description: 'Space-saving adjustable dumbbells ranging from 5lbs to 52.5lbs per hand.',
    image: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61',
    rating: 4.9,
    reviewCount: 670,
    inStock: false,
    category: 'Fitness',
    reviews: [
      {
        id: '28',
        productId: '10',
        userName: 'GymRat88',
        userImageUrl: 'https://images.unsplash.com/photo-1521119956141-ef544c7e5a8f',
        rating: 5,
        comment: 'Replaces a whole rack of dumbbells. Mechanisms are smooth.',
        title: 'Ultimate Space Saver',
        reviewDate: new Date('2024-01-20'),
      },
      {
        id: '29',
        productId: '10',
        userName: 'Lucas P.',
        userImageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e',
        rating: 5,
        comment: 'A bit pricey but worth every penny for a home gym.',
        title: 'Great Investment',
        reviewDate: new Date('2024-02-05'),
      },
      {
        id: '30',
        productId: '10',
        userName: 'Rachel W.',
        userImageUrl: 'https://images.unsplash.com/photo-1554151228-14d9def656e4',
        rating: 4,
        comment: 'They are quite long compared to normal dumbbells, takes some getting used to.',
        title: 'Effective but bulky',
        reviewDate: new Date('2024-02-28'),
      }
    ]
  },
  {
    id: 11,
    name: 'Velocity Jump Rope',
    price: 15.0,
    description: 'Tangle-free speed jump rope with ball bearings for high-intensity cardio.',
    image: 'https://images.unsplash.com/photo-1544033527-b192daee1f5b',
    rating: 4.5,
    reviewCount: 230,
    inStock: true,
    category: 'Fitness',
    reviews: [
      {
        id: '31',
        productId: '11',
        userName: 'Mike R.',
        userImageUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6',
        rating: 5,
        comment: 'So smooth! I can finally do double-unders.',
        title: 'Fast and smooth',
        reviewDate: new Date('2024-03-01'),
      },
      {
        id: '32',
        productId: '11',
        userName: 'Chloe S.',
        userImageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330',
        rating: 4,
        comment: 'Easy to adjust the length, but the wire can kink if you don\'t store it properly.',
        title: 'Great Cardio Tool',
        reviewDate: new Date('2024-03-12'),
      },
      {
        id: '33',
        productId: '11',
        userName: 'Jason D.',
        userImageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d',
        rating: 4,
        comment: 'Simple, effective, and cheap. Can’t ask for much more.',
        title: 'Good value',
        reviewDate: new Date('2024-03-25'),
      }
    ]
  },
  {
    id: 12,
    name: 'HydraPeak 32oz Bottle',
    price: 28.0,
    description: 'Vacuum insulated stainless steel water bottle that keeps drinks cold for 24 hours.',
    image: 'https://images.unsplash.com/photo-1664714628878-9d2aa898b9e3',
    rating: 4.7,
    reviewCount: 890,
    inStock: true,
    category: 'Fitness',
    reviews: [
      {
        id: '34',
        productId: '12',
        userName: 'Ethan B.',
        userImageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e',
        rating: 5,
        comment: 'Ice stayed solid for almost two full days in a hot car.',
        title: 'Amazing Insulation',
        reviewDate: new Date('2024-02-15'),
      },
      {
        id: '35',
        productId: '12',
        userName: 'Olivia N.',
        userImageUrl: 'https://images.unsplash.com/photo-1554151228-14d9def656e4',
        rating: 5,
        comment: 'Beautiful colors and the powder coating doesn’t chip.',
        title: 'Stylish and Durable',
        reviewDate: new Date('2024-03-02'),
      },
      {
        id: '36',
        productId: '12',
        userName: 'Liam W.',
        userImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d',
        rating: 4,
        comment: 'Great bottle, just a little heavy when full.',
        title: 'Solid Bottle',
        reviewDate: new Date('2024-03-18'),
      }
    ]
  },
  {
    id: 13,
    name: 'Pro-Chef Knife Set',
    price: 145.0,
    description: '6-piece forged German steel knife set with an acacia wood storage block.',
    image: 'https://images.unsplash.com/photo-1589071634465-75d7ce737fa8',
    rating: 4.8,
    reviewCount: 145,
    inStock: true,
    category: 'Kitchen',
    reviews: [
      {
        id: '37',
        productId: '13',
        userName: 'Gordon R.',
        userImageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e',
        rating: 5,
        comment: 'Incredibly sharp right out of the box. The weight balance is perfect.',
        title: 'Professional Grade',
        reviewDate: new Date('2024-01-22'),
      },
      {
        id: '38',
        productId: '13',
        userName: 'Linda K.',
        userImageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2',
        rating: 5,
        comment: 'The acacia block looks stunning on my countertop.',
        title: 'Beautiful and Sharp',
        reviewDate: new Date('2024-02-14'),
      },
      {
        id: '39',
        productId: '13',
        userName: 'Steven J.',
        userImageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d',
        rating: 4,
        comment: 'Great set, but the bread knife is a bit shorter than I prefer.',
        title: 'Mostly Perfect',
        reviewDate: new Date('2024-03-05'),
      }
    ]
  },
  {
    id: 14,
    name: 'AeroPress Coffee Maker',
    price: 39.95,
    description: 'The cult-classic coffee maker for smooth, rich, and grit-free coffee in minutes.',
    image: 'https://images.unsplash.com/photo-1667568976467-57c8964a257a',
    rating: 4.9,
    reviewCount: 3100,
    inStock: true,
    category: 'Kitchen',
    reviews: [
      {
        id: '40',
        productId: '14',
        userName: 'CoffeeLover92',
        userImageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb',
        rating: 5,
        comment: 'Better than my $500 espresso machine. Portable and easy to clean.',
        title: 'The Best Coffee Maker',
        reviewDate: new Date('2024-03-10'),
      },
      {
        id: '41',
        productId: '14',
        userName: 'Ben H.',
        userImageUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6',
        rating: 5,
        comment: 'Unbeatable for travel. Use it every morning in my hotel rooms.',
        title: 'Travel King',
        reviewDate: new Date('2024-03-22'),
      },
      {
        id: '42',
        productId: '14',
        userName: 'Carla V.',
        userImageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330',
        rating: 5,
        comment: 'Simple, fast, and the coffee is so smooth.',
        title: 'Must Buy',
        reviewDate: new Date('2024-04-01'),
      }
    ]
  },
  {
    id: 15,
    name: 'Digital Food Scale',
    price: 19.99,
    description: 'High-precision kitchen scale with a stainless steel finish and easy-to-read LCD.',
    image: 'https://plus.unsplash.com/premium_photo-1721522922185-f665934b902b',
    rating: 4.4,
    reviewCount: 420,
    inStock: true,
    category: 'Kitchen',
    reviews: [
      {
        id: '43',
        productId: '15',
        userName: 'BakerBob',
        userImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d',
        rating: 5,
        comment: 'Essential for bread making. Very accurate down to the gram.',
        title: 'Accurate and Sleek',
        reviewDate: new Date('2024-02-10'),
      },
      {
        id: '44',
        productId: '15',
        userName: 'Diana S.',
        userImageUrl: 'https://images.unsplash.com/photo-1554151228-14d9def656e4',
        rating: 4,
        comment: 'Nice display, but it turns off a bit too quickly to save battery.',
        title: 'Good, but auto-off is fast',
        reviewDate: new Date('2024-03-01'),
      },
      {
        id: '45',
        productId: '15',
        userName: 'Victor M.',
        userImageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e',
        rating: 4,
        comment: 'Simple to use, easy to clean the stainless surface.',
        title: 'Solid Kitchen Tool',
        reviewDate: new Date('2024-03-15'),
      }
    ]
  },
  {
    id: 16,
    name: 'Non-Stick Skillet (12")',
    price: 55.0,
    description: 'Hard-anodized aluminum skillet with a PFOA-free non-stick coating.',
    image: 'https://images.unsplash.com/photo-1590794056226-79ef3a8147e1',
    rating: 4.6,
    reviewCount: 215,
    inStock: true,
    category: 'Kitchen',
    reviews: [
      {
        id: '46',
        productId: '16',
        userName: 'Chef_Anna',
        userImageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2',
        rating: 5,
        comment: 'Eggs slide right off. No oil needed!',
        title: 'True Non-Stick',
        reviewDate: new Date('2024-02-20'),
      },
      {
        id: '47',
        productId: '16',
        userName: 'Paul L.',
        userImageUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6',
        rating: 4,
        comment: 'Nice weight to it. Feels much better than cheap grocery store pans.',
        title: 'Quality Pan',
        reviewDate: new Date('2024-03-05'),
      },
      {
        id: '48',
        productId: '16',
        userName: 'Grace H.',
        userImageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330',
        rating: 5,
        comment: 'Even heating across the whole surface. No hot spots.',
        title: 'Even Cooking',
        reviewDate: new Date('2024-03-18'),
      }
    ]
  },
  {
    id: 17,
    name: 'GlowSkin Face Serum',
    price: 32.0,
    description: 'Vitamin C and Hyaluronic acid serum for bright, hydrated, and youthful skin.',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be',
    rating: 4.7,
    reviewCount: 560,
    inStock: true,
    category: 'Personal Care',
    reviews: [
      {
        id: '49',
        productId: '17',
        userName: 'BeautyGuru91',
        userImageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb',
        rating: 5,
        comment: 'My skin has never looked so glowing. Cleared up my dark spots in 2 weeks.',
        title: 'Magic in a Bottle',
        reviewDate: new Date('2024-01-25'),
      },
      {
        id: '50',
        productId: '17',
        userName: 'Megan J.',
        userImageUrl: 'https://images.unsplash.com/photo-1554151228-14d9def656e4',
        rating: 4,
        comment: 'Smells amazing and feels lightweight. A bit pricey for the size though.',
        title: 'Great Serum',
        reviewDate: new Date('2024-02-14'),
      },
      {
        id: '51',
        productId: '17',
        userName: 'Tasha W.',
        userImageUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80',
        rating: 5,
        comment: 'Absorbs quickly and works great under makeup.',
        title: 'Smooth Application',
        reviewDate: new Date('2024-03-02'),
      }
    ]
  },
  {
    id: 18,
    name: 'Bamboo Toothbrush Set',
    price: 12.5,
    description: 'Pack of 4 biodegradable bamboo toothbrushes with charcoal-infused bristles.',
    image: 'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04',
    rating: 4.5,
    reviewCount: 180,
    inStock: true,
    category: 'Personal Care',
    reviews: [
      {
        id: '52',
        productId: '18',
        userName: 'EcoWarrior',
        userImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d',
        rating: 5,
        comment: 'Finally a plastic-free option that actually feels good to use.',
        title: 'Eco-Friendly and Effective',
        reviewDate: new Date('2024-02-01'),
      },
      {
        id: '53',
        productId: '18',
        userName: 'Sam R.',
        userImageUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6',
        rating: 4,
        comment: 'Bristles are soft but effective. Bamboo handle feels a bit different at first.',
        title: 'Good Quality',
        reviewDate: new Date('2024-02-20'),
      },
      {
        id: '54',
        productId: '18',
        userName: 'Lily T.',
        userImageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330',
        rating: 4,
        comment: 'Value for money is great for a pack of 4.',
        title: 'Great Value',
        reviewDate: new Date('2024-03-10'),
      }
    ]
  },
  {
    id: 19,
    name: 'Ionic Hair Dryer',
    price: 89.0,
    description: 'Professional-grade hair dryer with ionic technology to reduce frizz and heat damage.',
    image: 'https://images.unsplash.com/photo-1522338242992-e1a54906a8da',
    rating: 4.6,
    reviewCount: 340,
    inStock: true,
    category: 'Personal Care',
    reviews: [
      {
        id: '55',
        productId: '19',
        userName: 'HairPro_Kate',
        userImageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2',
        rating: 5,
        comment: 'Dries my thick hair in half the time. Minimal frizz!',
        title: 'Professional Performance',
        reviewDate: new Date('2024-01-30'),
      },
      {
        id: '56',
        productId: '19',
        userName: 'Monica G.',
        userImageUrl: 'https://images.unsplash.com/photo-1554151228-14d9def656e4',
        rating: 4,
        comment: 'A bit heavy to hold for long periods, but the results are worth it.',
        title: 'Excellent Results',
        reviewDate: new Date('2024-02-15'),
      },
      {
        id: '57',
        productId: '19',
        userName: 'Tyler F.',
        userImageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e',
        rating: 5,
        comment: 'The cold shot button actually stays cold. Great for setting styles.',
        title: 'Best Dryer I\'ve Had',
        reviewDate: new Date('2024-03-05'),
      }
    ]
  },
  {
    id: 20,
    name: 'Lavender Sleep Mask',
    price: 18.0,
    description: 'Weighted silk sleep mask filled with dried lavender for ultimate relaxation.',
    image: 'https://images.unsplash.com/photo-1615852152758-7a2b2a16f9ac',
    rating: 4.3,
    reviewCount: 95,
    inStock: true,
    category: 'Personal Care',
    reviews: [
      {
        id: '58',
        productId: '20',
        userName: 'Zoe B.',
        userImageUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80',
        rating: 5,
        comment: 'The smell of lavender is so soothing. I fall asleep instantly.',
        title: 'Deep Sleep at Last',
        reviewDate: new Date('2024-02-10'),
      },
      {
        id: '59',
        productId: '20',
        userName: 'Daniel P.',
        userImageUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6',
        rating: 4,
        comment: 'Weighted feel is nice, though the strap could be a bit more adjustable.',
        title: 'Very Relaxing',
        reviewDate: new Date('2024-03-01'),
      },
      {
        id: '60',
        productId: '20',
        userName: 'Karen L.',
        userImageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2',
        rating: 4,
        comment: 'Soft silk material feels great against the skin.',
        title: 'Premium Feel',
        reviewDate: new Date('2024-03-12'),
      }
    ]
  },
  {
    id: 21,
    name: 'Lumixia Smart Watch Series 5',
    price: 199.99,
    description: 'A sleek, waterproof smartwatch featuring advanced heart rate monitoring, GPS tracking, and a 7-day battery life.',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30',
    rating: 4.8,
    reviewCount: 1240,
    inStock: true,
    category: 'Electronics',
    reviews: [
      {
        id: '61',
        productId: '21',
        userName: 'FitnessFanatic',
        userImageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e',
        rating: 5,
        comment: 'The GPS tracking is incredibly accurate on my morning runs.',
        title: 'Perfect Training Partner',
        reviewDate: new Date('2024-01-18'),
      },
      {
        id: '62',
        productId: '21',
        userName: 'Amanda T.',
        userImageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330',
        rating: 5,
        comment: '7-day battery life is no joke. I only charge it once a week.',
        title: 'Finally, a watch that lasts',
        reviewDate: new Date('2024-02-10'),
      },
      {
        id: '63',
        productId: '21',
        userName: 'Robert S.',
        userImageUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6',
        rating: 4,
        comment: 'Sleek design looks good even with a suit.',
        title: 'Stylish and Smart',
        reviewDate: new Date('2024-03-05'),
      }
    ]
  },
  {
    id: 22,
    name: 'Artisan Ceramic Pour-Over Set',
    price: 45.0,
    description: 'Hand-glazed ceramic coffee dripper and server. Perfect for the home barista who values both style and flavor.',
    image: 'https://images.unsplash.com/photo-1544233726-9f1d2b27be8b',
    rating: 4.5,
    reviewCount: 89,
    inStock: true,
    category: 'Home & Kitchen',
    reviews: [
      {
        id: '64',
        productId: '22',
        userName: 'BaristaBeth',
        userImageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2',
        rating: 5,
        comment: 'Beautiful glaze. It makes my morning ritual feel like art.',
        title: 'Stunning Craftsmanship',
        reviewDate: new Date('2024-02-14'),
      },
      {
        id: '65',
        productId: '22',
        userName: 'Greg W.',
        userImageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d',
        rating: 4,
        comment: 'Heats up well and keeps the coffee warm. Handle is a bit small.',
        title: 'Great Flavor',
        reviewDate: new Date('2024-03-01'),
      },
      {
        id: '66',
        productId: '22',
        userName: 'Hannah M.',
        userImageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb',
        rating: 5,
        comment: 'Perfect gift for any coffee lover. Packaging was very secure.',
        title: 'Excellent Gift',
        reviewDate: new Date('2024-03-15'),
      }
    ]
  },
  {
    id: 23,
    name: 'Vanguard Noise-Cancelling Headphones',
    price: 299.0,
    description: 'Experience pure sound with industry-leading active noise cancellation and ultra-soft memory foam ear cups.',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e',
    rating: 4.9,
    reviewCount: 2150,
    inStock: false,
    category: 'Electronics',
    reviews: [
      {
        id: '67',
        productId: '23',
        userName: 'Audiophile_Dan',
        userImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d',
        rating: 5,
        comment: 'ANC is better than the top competitors. Total silence on flights.',
        title: 'Best Noise Cancellation',
        reviewDate: new Date('2024-01-10'),
      },
      {
        id: '68',
        productId: '23',
        userName: 'Sara J.',
        userImageUrl: 'https://images.unsplash.com/photo-1554151228-14d9def656e4',
        rating: 5,
        comment: 'So comfortable I forget I’m wearing them. Worth the price.',
        title: 'Incredible Comfort',
        reviewDate: new Date('2024-02-05'),
      },
      {
        id: '69',
        productId: '23',
        userName: 'Kevin L.',
        userImageUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6',
        rating: 5,
        comment: 'The touch controls are intuitive and responsive.',
        title: 'Premium Experience',
        reviewDate: new Date('2024-02-28'),
      }
    ]
  },
  {
    id: 24,
    name: 'ErgoLift Standing Desk Converter',
    price: 155.5,
    description: 'Transition from sitting to standing in seconds with our gas-spring assisted desk riser. Fits dual monitors.',
    image: 'https://images.unsplash.com/photo-1593642702821-c8da6771f0c6',
    rating: 4.2,
    reviewCount: 456,
    inStock: true,
    category: 'Office',
    reviews: [
      {
        id: '70',
        productId: '24',
        userName: 'OfficeWorker9to5',
        userImageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e',
        rating: 4,
        comment: 'Very stable even at full height. A bit heavy to lift out of the box.',
        title: 'Solid and Stable',
        reviewDate: new Date('2024-02-12'),
      },
      {
        id: '71',
        productId: '24',
        userName: 'Kimberly R.',
        userImageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2',
        rating: 5,
        comment: 'Great for my posture. The keyboard tray is at a perfect angle.',
        title: 'Saved my posture',
        reviewDate: new Date('2024-03-01'),
      },
      {
        id: '72',
        productId: '24',
        userName: 'Mike D.',
        userImageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d',
        rating: 3,
        comment: 'Takes up quite a bit of desk space, make sure you measure first.',
        title: 'Bulky but functional',
        reviewDate: new Date('2024-03-20'),
      }
    ]
  },
  {
    id: 25,
    name: 'Eco-Stride Recycled Sneakers',
    price: 85.0,
    description: 'Sustainable footwear made from ocean-bound plastics. Lightweight, breathable, and carbon-neutral.',
    image: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86',
    rating: 4.6,
    reviewCount: 312,
    inStock: true,
    category: 'Footwear',
    reviews: [
      {
        id: '73',
        productId: '25',
        userName: 'Walker_Green',
        userImageUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6',
        rating: 5,
        comment: 'Unbelievably lightweight. Feels like walking on air.',
        title: 'Comfortable and Sustainable',
        reviewDate: new Date('2024-03-05'),
      },
      {
        id: '74',
        productId: '25',
        userName: 'Emily C.',
        userImageUrl: 'https://images.unsplash.com/photo-1554151228-14d9def656e4',
        rating: 4,
        comment: 'Great summer shoe. Very breathable, but not for rainy days!',
        title: 'Perfect for Summer',
        reviewDate: new Date('2024-03-18'),
      },
      {
        id: '75',
        productId: '25',
        userName: 'Jacob B.',
        userImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d',
        rating: 5,
        comment: 'Love the mission behind these shoes. They look great too.',
        title: 'Stylish Ethics',
        reviewDate: new Date('2024-04-01'),
      }
    ]
  },
  {
    id: 26,
    name: 'Midnight Botanical Candle',
    price: 22.0,
    description: 'Soy-based wax candle with notes of lavender, sandalwood, and amber. Burn time: 50 hours.',
    image: 'https://images.unsplash.com/photo-1603006905003-be475563bc59',
    rating: 4.7,
    reviewCount: 112,
    inStock: true,
    category: 'Home Decor',
    reviews: [
      {
        id: '76',
        productId: '26',
        userName: 'CandleQueen',
        userImageUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80',
        rating: 5,
        comment: 'The scent fills the whole house without being overpowering.',
        title: 'Absolute Favorite Scent',
        reviewDate: new Date('2024-02-20'),
      },
      {
        id: '77',
        productId: '26',
        userName: 'Thomas V.',
        userImageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e',
        rating: 5,
        comment: 'Burns very evenly. No tunneling at all.',
        title: 'High Quality Wax',
        reviewDate: new Date('2024-03-10'),
      },
      {
        id: '78',
        productId: '26',
        userName: 'Sophia L.',
        userImageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330',
        rating: 4,
        comment: 'The jar is beautiful and I plan to reuse it after the candle is gone.',
        title: 'Lovely Packaging',
        reviewDate: new Date('2024-03-25'),
      }
    ]
  }
] satisfies Product[] as Product[];